### ISSUE TITLE
Add ability to specify version of container when running

### ISSUE THREAD

**Issue by jbwexler** [ReproNim/containers#114]
For example, I sometimes want to run an older version of fmriprep. Is there already an easy way to do this?

**Comment by yarikoptic** [comment]
you just create a dedicated versioned entry within your `.datalad/config` e.g.

```
[datalad "containers.bids-fmriprep-20.2.0"]
    cmdexec = {img_dspath}/scripts/singularity_cmd run {img} {cmd}
    image = images/bids/bids-fmriprep--20.2.0.sing
```

so you have all flexibility you need , just need to explicitly "specify" it in `.datalad/config` and it cannot be an option to `datalad containers-run` since it would then somehow be aware of how container images are versioned.  Feel free to reopen if there is more to discuss.

**Comment by jbwexler** [comment]
Ah ok thanks, I never thought to create a new entry for each version I need. In an ideal world, I could just include a flag in reproman or containers-run like `container=code/containers/bids-fmriprep --version=23.1.4`. But I see why that's challenging. Maybe that would require some sort of standardization of how versions are specified in the container filenames? Or what if you had something like:

```
[datalad "containers.bids-fmriprep]
    cmdexec = {img_dspath}/scripts/singularity_cmd run {img} {cmd}
    image = images/bids/bids-fmriprep--{version}.sing
    default_version = 20.2.0
```

**Comment by yarikoptic** [comment]
hm, that does make  sense given that we have already other substitutions there, let's reopen and transfer to where it belongs - datalad-container.

**Comment by yarikoptic** [comment]
actually can't transfer across organizations ;)  filed

- https://github.com/datalad/datalad-container/issues/266
