### ISSUE TITLE
issue with fmriprep v21.0.0 image

### ISSUE THREAD

**Issue by jbwexler** [ReproNim/containers#65]
The image is only 2.2GB whereas it should be 5.1GB. And it gives the following error when run: "/.singularity.d/runscript: 3: exec: /opt/conda/bin/fmriprep: Exec format error"

I don't think it's an issue with fmriprep as the image works fine when downloaded this way: `singularity build fmriprep-21.0.0.simg docker://nipreps/fmriprep:21.0.0`

**Comment by djarecka** [comment]
have the same error

**Comment by yarikoptic** [comment]
Thank you! I will have a look tomorrow - something should've gone wrong I guess

**Comment by yarikoptic** [comment]
Thank you @jbwexler for alerting and @djarecka for confirming the issue.   Update dataset and try again now.

The reason was -- the partition docker uses for its `.cache` got filled up by it!  That lead singularity (still using 2.6 there) to start puking all kinds of errors but script itself proceeded as nothing bad happened.  Unfortunately in a rush to address the issue I just removed the cache so didn't drill down to fix situation so it would not manifest in the future.  Filed a dedicated https://github.com/ReproNim/containers/issues/66 for that, and since AFAIK fmriprep image is fixed, will close this one.
